version: '3.4'
networks:
  fund-islam-net:
    name: fund-islam-net

services:
  local-service:
    image: aliqamarlabs/fund-islam-localservice
    build:
      context: .
      dockerfile: local-service/Dockerfile
    networks:
      - fund-islam-net
    dns:
      - 8.8.8.8

  redis:
    image: "redis:6"
    networks:
      - fund-islam-net
    dns:
      - 8.8.8.8

  initiatives:
    image: aliqamarlabs/fund-islam-initiatives
    build:
      context: .
      dockerfile: /initiatives/Dockerfile
    networks:
      - fund-islam-net
    dns:
      - 8.8.8.8

  common:
    image: aliqamarlabs/fund-islam-common
    build:
      context: .
      dockerfile: /common/Dockerfile
    networks:
      - fund-islam-net
    dns:
      - 8.8.8.8

  startup-businesses:
    image: aliqamarlabs/fund-islam-startup-businesses
    build:
      context: .
      dockerfile: /startup-businesses/Dockerfile
    networks:
      - fund-islam-net
    dns:
      - 8.8.8.8

  users:
    image: aliqamarlabs/fund-islam-users
    build:
      context: .
      dockerfile: /users/Dockerfile
    networks:
      - fund-islam-net
    dns:
      - 8.8.8.8
